name: Github Changelog or History Generator 
description: Github Changelog/History Generator
author: tj-actions
inputs:
  token:
    description: 'GITHUB_TOKEN or a Repo scoped PAT'
    required: true
    default: ${{ github.token }}
  output:
    description: 'Output file'
    required: false
    default: "CHANGELOG.md"

runs:
  using: 'docker'
  image: 'docker://ghcr.io/tj-actions/github-changelog-generator:latest'
branding:
  icon: file-text
  color: white
