name: Github Changelog or History Generator 
description: Github Changelog/History Generator
author: tj-actions
inputs:
  token:
    description: '[GITHUB_TOKEN](https://docs.github.com/en/free-pro-team@latest/actions/reference/authentication-in-a-workflow#using-the-github_token-in-a-workflow) or a repo scoped [Personal Access Token](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token)'
    required: true
    default: ${{ github.token }}
  output:
    description: 'The changelog output file'
    required: false
    default: "CHANGELOG.md"

runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: '/entrypoint.sh'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.output }}
branding:
  icon: file-text
  color: white
